import type { ActionTypesBase, StateBase } from './types';

export const ActionTypes: ActionTypesBase = {
  DEVICE_DELETE_REQUEST: '@oauth/DEVICE_DELETE_REQUEST',
  DEVICE_DELETE_SUCCESS: '@oauth/DEVICE_DELETE_SUCCESS',
  DEVICE_DELETE_FAILURE: '@oauth/DEVICE_DELETE_FAILURE',

  DEVICE_LIST_REQUEST: '@oauth/DEVICE_LIST_REQUEST',
  DEVICE_LIST_SUCCESS: '@oauth/DEVICE_LIST_SUCCESS',
  DEVICE_LIST_FAILURE: '@oauth/DEVICE_LIST_FAILURE',

  DEVICE_ADD_REQUEST: '@oauth/DEVICE_ADD_REQUEST',
  DEVICE_ADD_SUCCESS: '@oauth/DEVICE_ADD_SUCCESS',
  DEVICE_ADD_FAILURE: '@oauth/DEVICE_ADD_FAILURE',

  DEVICE_FIND_REQUEST: '@oauth/DEVICE_FIND_REQUEST',
  DEVICE_FIND_SUCCESS: '@oauth/DEVICE_FIND_SUCCESS',
  DEVICE_FIND_FAILURE: '@oauth/DEVICE_FIND_FAILURE',

  DEVICE_UPDATE_REQUEST: '@oauth/DEVICE_UPDATE_REQUEST',
  DEVICE_UPDATE_SUCCESS: '@oauth/DEVICE_UPDATE_SUCCESS',
  DEVICE_UPDATE_FAILURE: '@oauth/DEVICE_UPDATE_FAILURE',
};

export const InitialState: StateBase = {
  item: null,
  itemEdit: null,
  error: false,
  loading: false,
};
